---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-init
  namespace: data-services
data:
  init.ldif: |
    dn: dc=cajafinanciera,dc=com
    objectClass: top
    objectClass: dcObject
    objectClass: organization
    o: Caja Financiera
    dc: cajafinanciera

    dn: ou=Groups,dc=cajafinanciera,dc=com
    objectClass: organizationalUnit
    ou: Groups

    dn: ou=Users,dc=cajafinanciera,dc=com
    objectClass: organizationalUnit
    ou: Users

    dn: ou=DataAnalytics,ou=Groups,dc=cajafinanciera,dc=com
    objectClass: organizationalUnit
    ou: DataAnalytics

    dn: ou=DataModelers,ou=DataAnalytics,ou=Groups,dc=cajafinanciera,dc=com
    objectClass: organizationalUnit
    ou: DataModelers

    dn: cn=devs,ou=DataModelers,ou=DataAnalytics,ou=Groups,dc=cajafinanciera,dc=com
    objectClass: groupOfNames
    cn: devs
    member: cn=usuario1,ou=Users,dc=cajafinanciera,dc=com

    dn: cn=admins,ou=DataModelers,ou=DataAnalytics,ou=Groups,dc=cajafinanciera,dc=com
    objectClass: groupOfNames
    cn: admins
    member: cn=usuario2,ou=Users,dc=cajafinanciera,dc=com

    dn: cn=usuario1,ou=Users,dc=cajafinanciera,dc=com
    objectClass: inetOrgPerson
    sn: Uno
    givenName: Usuario
    cn: usuario1
    uid: usuario1
    userPassword: password1

    dn: cn=usuario2,ou=Users,dc=cajafinanciera,dc=com
    objectClass: inetOrgPerson
    sn: Dos
    givenName: Usuario
    cn: usuario2
    uid: usuario2
    userPassword: password2

    dn: cn=ldapreader24g890uwef,ou=Users,dc=cajafinanciera,dc=com
    objectClass: inetOrgPerson
    sn: ReadOnly
    givenName: LDAP User Lookup
    cn: ldapreader24g890uwef
    uid: ldapreader24g890uwef
    userPassword: 24f98ifwe9ua

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: data-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: mario21ic/openldap:latest
          env:
            - name: LDAP_ROOT
              value: "dc=cajafinanciera,dc=com"
            - name: LDAP_ADMIN_USERNAME
              value: "adminpSedf824"
            - name: LDAP_ADMIN_PASSWORD
              value: "adminszdf8923r"
          ports:
            - containerPort: 1389
          volumeMounts:
            - name: ldif-volume
              mountPath: /ldifs
              readOnly: true
      volumes:
        - name: ldif-volume
          configMap:
            name: openldap-init

---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: data-services
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 1389
      nodePort: 31389
  
