apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: data-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-03-12T18-04-18Z
          imagePullPolicy: IfNotPresent
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          envFrom:
            - configMapRef:
                name: minio-config
            - secretRef:
                name: minio-secret
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    export MC_ALIAS_USER="${MINIO_ROOT_USER}" && \
                    export MC_ALIAS_PASS="${MINIO_ROOT_PASSWORD}" && \
                    sleep 5 && \
                    mc alias set local http://localhost:9000 "$MC_ALIAS_USER" "$MC_ALIAS_PASS" && \
                    mc admin config reset local identity_openid:_ && \
                    mc mb local/warehouse-dev || true && \
                    mc mb local/warehouse-prd || true && \
                    mc mb local/kyuubi || true && \
                    mc mb local/lhchdev || true && \
                    mc mb local/lhchprd || true

          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          hostPath:
            path: /mnt/nfs-minio
            type: Directory