---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  namespace: airflow
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nfs-logs-airflow"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: airflow-logs-pv  # Add this line to bind to the PV
---
