
CREATE TABLE dbo.STG_CLIMCLIENTES (
    CCODCLIENTE          VARCHAR(12)     NULL,
    CNOMCLIENTE          VARCHAR(120)    NULL,
    CCODSBS              VARCHAR(15)     NULL,
    CCODCLAPER           VARCHAR(1)      NULL,
    DFECHINICMAC         DATETIME2(7)    NULL,
    DFECHINISISF         DATETIME2(7)    NULL,
    CCORELECLI           VARCHAR(60)     NULL,
    CCODCIIU             VARCHAR(4)      NULL,
    CCODTIPODOCID        VARCHAR(1)      NULL,
    CNRODOCIDE           VARCHAR(20)     NULL,
    CNRODOCTRI           VARCHAR(40)     NULL,
    CNROTELPER           VARCHAR(12)     NULL,
    CDIRCLIENTE          VARCHAR(200)    NULL,
    NMONINVING           NUMERIC(12,2)   NULL,
    CCTRLCLIEL           VARCHAR(1)      NULL,
    FECULTACTUALIZACION  DATETIME2(7)    NULL
);



CREATE TABLE dbo.STG_CLIMDIRECC (
    CCODCLIENTE         VARCHAR(12)     NULL,
    CCODDIRCLI          NUMERIC(19,0)   NULL,
    CCODPAIS            VARCHAR(3)      NULL,
    CCODDEPART          VARCHAR(2)      NULL,
    CCODPROVIN          VARCHAR(2)      NULL,
    CCODDISTRI          VARCHAR(2)      NULL,
    CCODZONA            VARCHAR(4)      NULL,
    CDIRCLIENTE         VARCHAR(200)    NULL,
    CNROTELFIJ          VARCHAR(12)     NULL,
    CAÑORESDOM          VARCHAR(4)      NULL,
    CCODTIPVIA          VARCHAR(2)      NULL,
    BDIRPREDET          VARCHAR(1)      NULL,
    FECULTACTUALIZACION DATETIME2(7)    NULL,
    CDIRREFCLIENTE      VARCHAR(200)    NULL
);


CREATE TABLE dbo.STG_CLIMPERJUR (
    CCODCLIENTE         VARCHAR(12)     NULL,
    DFECCONSTI          DATETIME2(7)    NULL,
    FECULTACTUALIZACION DATETIME2(7)    NULL
);


CREATE TABLE dbo.STG_CLIMPERNAT (
    CCODCLIENTE         VARCHAR(12)     NULL,
    DFECNACCLI          DATETIME2(7)    NULL,
    CCODSEXO            VARCHAR(1)      NULL,
    CCODPAINAC          VARCHAR(3)      NULL,
    CCODDEPNAC          VARCHAR(2)      NULL,
    CCODPRONAC          VARCHAR(2)      NULL,
    CCODDISNAC          VARCHAR(2)      NULL,
    CCODZONNAC          VARCHAR(3)      NULL,
    CCODESTCIV          VARCHAR(1)      NULL,
    FECULTACTUALIZACION DATETIME2(7)    NULL
);


CREATE TABLE dbo.STG_DABOGADOJUD (
    CODABOGADOJUD        VARCHAR(6)     NULL,
    NOMABOGADOJUD        VARCHAR(120)   NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);

-- se puede considerar clave primaria---

CREATE TABLE dbo.STG_DACTIVIDADECONOMICA (
    CCODCIIU             VARCHAR(4)      NOT NULL,
    CDESACTIVI           VARCHAR(180)    NULL,
    CCODCATEGO           VARCHAR(1)      NULL,
    FECULTACTUALIZACION  DATETIME2(7)    NULL
);
------------------------


CREATE TABLE dbo.STG_DADEUDADO (
    CCODCORADE           VARCHAR(15)     NULL,
    CDESADEUDA           VARCHAR(60)     NULL,
    FECULTACTUALIZACION  DATETIME2(7)    NULL
);


CREATE TABLE dbo.STG_DADMINISTRADOR (
    CCODPERSON VARCHAR(6) NOT NULL,
    CNOMPERSON VARCHAR(120) NULL,
    DFECFINROT DATETIME NULL,
    CCODOFICIN VARCHAR(3) NULL,
    FECULTACTUALIZACION DATETIME NULL,
    CONSTRAINT PK_STG_DADMINISTRADOR PRIMARY KEY (CCODPERSON)
);


CREATE TABLE dbo.STG_DAGENCIA (
    CODAGENCIA         VARCHAR(3)     NULL,
    DESAGENCIA         VARCHAR(100)   NULL,
    CODZONACOMERCIAL   VARCHAR(3)     NULL,
    DESZONACOMERCIAL   VARCHAR(60)    NULL,
    LONGITUD           VARCHAR(1)     NOT NULL,
    LATITUD            VARCHAR(1)     NOT NULL,
    CODTIPOAGENCIA     VARCHAR(1)     NULL,
    DESTIPOAGENCIA     VARCHAR(100)   NULL,
    PKUBIGEO           INT            NULL,
    FECHAINICIOVIG     INT            NULL,
    FECHAFINVIG        INT            NULL,
    FLAGACTIVO         BIT            NULL,
    CCODDEPART         VARCHAR(2)     NULL,
    CCODPROVIN         VARCHAR(2)     NULL,
    CCODDISTRI         VARCHAR(2)     NULL,
    CCODZONA           VARCHAR(3)     NULL
);



CREATE TABLE dbo.STG_DASESOR (
    CODASESOR           VARCHAR(6)      NULL,
    NOMASESOR           VARCHAR(120)    NULL,
    FUENTE              VARCHAR(20)     NULL,
    FECULTACTUALIZACION DATETIME2(7)    NULL
);



CREATE TABLE dbo.STG_DASESORNIVEL (
    NCODPAPAPR           INT            NOT NULL,
    CCODNIVEL            VARCHAR(2)     NOT NULL,
    CCODSUBNIV           VARCHAR(1)     NOT NULL,
    CCODCLASUB           VARCHAR(2)     NOT NULL,
    CDESCLASUB           VARCHAR(150)   NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DAUXILIARREGIONAL (
    cCodPerson           CHAR(6)        NOT NULL,
    cNomPerson           VARCHAR(120)   NULL,
    DFECFINROT           DATETIME       NOT NULL,
    nCodZona             INT            NOT NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL
);



CREATE TABLE dbo.STG_DCALIFICACIONCREDITICIA (
    CCODCLACAR           VARCHAR(2)     NULL,
    CDESCLACAR           VARCHAR(50)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DCANALDESEMBOLSO (
    CCODTIPDES           VARCHAR(1)     NULL,
    CDESTIPDES           VARCHAR(80)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DCLASEPERSONA (
    CCODCLAPER           VARCHAR(1)     NOT NULL,
    CDESCLAPER           VARCHAR(100)   NULL,
    CDESCORTA            VARCHAR(20)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DCLIENTE (
    CCODCLIENTE        VARCHAR(12)     NULL,
    CNOMCLIENTE        VARCHAR(120)    NULL,
    CCODSBS            VARCHAR(15)     NULL,
    CCODCLAPER         VARCHAR(1)      NULL,
    DFECINICMAC        DATETIME2(7)    NULL,
    DFECINISISF        DATETIME2(7)    NULL,
    CCORELECLI         VARCHAR(60)     NULL,
    CCODCIIU           VARCHAR(4)      NULL,
    CCODTIPODOCID      VARCHAR(1)      NULL,
    CNRODOCIDE         VARCHAR(20)     NULL,
    CNRODOCTRI         VARCHAR(40)     NULL,
    CNROTELPER         VARCHAR(12)     NULL,
    NMONINVING         NUMERIC(12,2)   NULL,
    FECHANACIMIENTO    DATETIME2(7)    NULL,
    CCODSEXO           VARCHAR(1)      NULL,
    CCODPAINAC         VARCHAR(3)      NULL,
    CCODDEPNAC         VARCHAR(2)      NULL,
    CCODPRONAC         VARCHAR(2)      NULL,
    CCODDISNAC         VARCHAR(2)      NULL,
    CCODZONNAC         VARCHAR(3)      NULL,
    CCODPAIS           VARCHAR(3)      NULL,
    CCODDEPART         VARCHAR(2)      NULL,
    CCODPROVIN         VARCHAR(2)      NULL,
    CCODDISTRI         VARCHAR(2)      NULL,
    CCODZONA           VARCHAR(4)      NULL,
    CCODTIPVIA         VARCHAR(2)      NULL,
    CDIRCLIENTE        VARCHAR(200)    NULL,
    CNROTELFJ          VARCHAR(12)     NULL,
    CANORESDOM         VARCHAR(4)      NULL,
    CDSESTCIV          VARCHAR(50)     NULL,
    CCODEMPLEADOR      VARCHAR(12)     NULL,
    CCODTIPFIN         VARCHAR(1)      NULL,
    NMONINGNET         NUMERIC(12,2)   NULL,
    CANOINIFIN         VARCHAR(4)      NULL,
    DFECREGFIN         DATETIME2(7)    NULL,
    CCODACTIVI         VARCHAR(6)      NULL,
    CNOMEMP            VARCHAR(120)    NULL,
    CNRODOCEMP         VARCHAR(15)     NULL,
    CCODDEPARTFIN      VARCHAR(2)      NULL,
    CCODPROVINFIN      VARCHAR(2)      NULL,
    CCODDISTRIFIN      VARCHAR(2)      NULL,
    CCODZONAFIN        VARCHAR(3)      NULL,
    CDIREMP            VARCHAR(120)    NULL,
    CNROTELEMP         VARCHAR(12)     NULL,
    CCODTIPVIAFIN      VARCHAR(2)      NULL,
    CDIRREFCLIENTE     VARCHAR(200)    NULL
);


CREATE TABLE dbo.STG_DCOMITE (
    CCODCOMITE           VARCHAR(3)     NULL,
    CDESCRITIP           VARCHAR(100)   NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);

CREATE TABLE dbo.STG_DCONCEPTOOPERACION (
    CCODCONOPE           VARCHAR(4)     NOT NULL,
    CDESCONOPE           VARCHAR(70)    NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DCONDICIONCONTABLE (
    CCONDICCON           VARCHAR(2)     NULL,
    CDESCONCRE           VARCHAR(20)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DCUENTACREDITO (
    cCodCtaCre         CHAR(18)        NOT NULL,
    cCodSolCre         CHAR(10)        NULL,
    cEstCreCon         CHAR(1)         NULL,
    cCodClaCar         CHAR(2)         NULL,
    nPorProCar         NUMERIC(14,4)   NULL,
    cCodClaUri         CHAR(2)         NULL,
    nPorProUri         NUMERIC(14,4)   NULL,
    cCodClaUriAE       CHAR(2)         NULL,
    nPorProUriAE       NUMERIC(9,4)    NULL,
    nNumCuoApr         INT             NULL,
    nNumDiaApr         INT             NULL,
    nNumDiaGra         INT             NULL,
    nDiaFecFij         SMALLINT        NULL,
    lCuotaCons         BIT             NULL,
    cCodTipCuo         CHAR(1)         NULL,
    cTipPeriodo        CHAR(1)         NULL,
    cLibAmoCre         CHAR(1)         NULL,
    cUltNumDoc         CHAR(6)         NULL,
    nNumDesemb         SMALLINT        NULL,
    nMonAprCre         NUMERIC(14,2)   NULL,
    nMonCapDes         NUMERIC(14,2)   NULL,
    nMonCapPag         NUMERIC(14,2)   NULL,
    nMonIntPro         NUMERIC(14,2)   NULL,
    nMonIntFec         NUMERIC(14,2)   NULL,
    nMonIntPag         NUMERIC(14,2)   NULL,
    nMonGasPro         NUMERIC(14,2)   NULL,
    nMonGasPag         NUMERIC(14,2)   NULL,
    nMonMorPro         NUMERIC(14,2)   NULL,
    nMonMorPag         NUMERIC(14,2)   NULL,
    cCodTipCre         CHAR(2)         NULL,
    cCodProduc         CHAR(2)         NULL,
    cCodSubPro         CHAR(2)         NULL,
    cCodTipRec         CHAR(2)         NULL,
    cCodRecurs         CHAR(2)         NULL,
    cCodTipMon         CHAR(1)         NULL,
    cCodPlazo          CHAR(1)         NULL,
    cCodModCre         CHAR(2)         NULL,
    cCodDesCre         CHAR(2)         NULL,
    nNroLinFin         INT             NULL,
    cTipTasCom         CHAR(2)         NULL,
    nTasIntCom         NUMERIC(14,4)   NULL,
    cTipTasMor         CHAR(2)         NULL,
    nNroTasMor         INT             NULL,
    nTasIntMor         NUMERIC(14,4)   NULL,
    nDiaAtrCre         INT             NULL,
    nDiaAtrAnt         INT             NULL,
    nDiaAtrAcu         INT             NULL,
    nDiaAtrMax         INT             NULL,
    dFecUltPag         DATETIME        NULL,
    dFecCulCre         DATETIME        NULL,
    dFecGenCre         DATETIME        NULL,
    dFecDesRef         DATETIME        NULL,
    dFecDesCre         DATETIME        NULL,
    dFecModCre         DATETIME        NULL,
    dFecResCre         DATETIME        NULL,
    dFecRepCre         DATETIME        NULL,
    dFecProSld         DATETIME        NULL,
    nTipCamDes         NUMERIC(8,4)    NULL,
    cCodUsuAna         CHAR(6)         NULL,
    cCodUsuPro         CHAR(6)         NULL,
    cCodUsuRes         CHAR(6)         NULL,
    cCodUsuRep         CHAR(6)         NULL,
    nInDevAFEc         NUMERIC(14,2)   NULL,
    nInDevAAnt         NUMERIC(14,2)   NULL,
    nInDevADia         NUMERIC(14,2)   NULL,
    nInDevAFEa         NUMERIC(14,2)   NULL,
    nSalCapDia         NUMERIC(14,2)   NULL,
    nSalCapAnt         NUMERIC(14,2)   NULL,
    lConConven         BIT             NULL,
    cCodConven         CHAR(6)         NULL,
    cCodIntCon         CHAR(5)         NULL,
    cCreNorRef         CHAR(1)         NULL,
    cCodRefina         CHAR(1)         NULL,
    cCodReestr         CHAR(1)         NULL,
    cCodReprog         CHAR(1)         NULL,
    cMarIngJud         CHAR(1)         NULL,
    cCodJudici         CHAR(1)         NULL,
    cCodCastig         CHAR(1)         NULL,
    cCodNotSis         CHAR(2)         NULL,
    cCodNotAna         CHAR(2)         NULL,
    dDesCofide         CHAR(3)         NULL,
    cCodFuelng         CHAR(3)         NULL,
    cCodInsCre         CHAR(3)         NULL,
    cCreRapido         CHAR(10)        NULL,
    lRedDefCre         BIT             NULL,
    nNumRefCre         SMALLINT        NULL,
    cConRefAgr         CHAR(1)         NULL,
    cCodInsFin         CHAR(3)         NULL,
    IdConexion         INT             NULL,
    cCodUsuBlo         CHAR(6)         NULL,
    cCodActivi         CHAR(6)         NULL,
    nMonTasGar         NUMERIC(14,2)   NULL,
    lFlgMiViVi         BIT             NULL,
    nMonCuoIni         NUMERIC(14,2)   NULL,
    nSalIntDev         NUMERIC(14,2)   NULL,
    cCodCTAINT         VARCHAR(40)     NULL,
    cCodCTACAP         VARCHAR(40)     NULL,
    cNroInfPro         VARCHAR(50)     NULL,
    dFecAprInf         DATETIME        NULL,
    cUsuAprInf         CHAR(6)         NULL,
    cCodOrdPag         CHAR(13)        NULL,
    nMonSalNor         NUMERIC(14,2)   NULL,
    nMonSalVen         NUMERIC(14,2)   NULL,
    cCondicNor         CHAR(2)         NULL,
    cCondicVen         CHAR(2)         NULL,
    cCodCtaNor         VARCHAR(40)     NULL,
    cCodCtaVen         VARCHAR(40)     NULL,
    nMonSalRep         NUMERIC(14,2)   NULL,
    cIndNueRep         CHAR(1)         NULL,
    cCodOficin         CHAR(3)         NULL,
    cRieCreCam         CHAR(1)         NULL,
    cAuditUser         VARCHAR(30)     NULL,
    cAuditStation      VARCHAR(30)     NULL,
    cAuditClient       VARCHAR(50)     NULL,
    dAuditDate         DATETIME        NULL,
    nCosEfeAct         NUMERIC(14,4)   NULL,
    FECULTACTUALIZACION DATETIME       NOT NULL
);



CREATE TABLE dbo.STG_DDESTINOCREDITO (
    CCODDESCRE           VARCHAR(2)     NULL,
    CDESCRIDES           VARCHAR(50)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DDESTINOPIVOT_1 (
    PKSOLICITUD   INT           NOT NULL,
    CODSOLICITUD  VARCHAR(10)   NOT NULL
);


CREATE TABLE dbo.STG_DDESTINOPIVOT_2 (
    PKSOLICITUD          INT           NOT NULL,
    DESDESTINOCREDITO    VARCHAR(50)   NOT NULL
);



CREATE TABLE dbo.STG_DDESTINOPIVOT_3 (
    PKSOLICITUD   INT           NOT NULL,
    DESTINO       VARCHAR(100)  NULL
);


CREATE TABLE dbo.STG_DDESTINOPIVOT_4 (
    PKSOLICITUD   INT           NOT NULL,
    DESTINO       VARCHAR(100)  NULL
);


CREATE TABLE dbo.STG_DENTIDADFINANCIERA (
    CCODIFI              VARCHAR(5)     NULL,
    CNOMIFI              VARCHAR(256)   NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DESTADOCREDITO (
    CESTCRECON           VARCHAR(1)     NOT NULL,
    CDESCRIEST           VARCHAR(30)    NULL,
    FECACTUALIZACION     DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DEVALUACION (
    nNumEvaMes           INT             NOT NULL,
    cCodSolCre           VARCHAR(10)     NULL,
    nValExcCre           NUMERIC(14,2)   NULL,
    TIPOEVALUACION       VARCHAR(20)     NOT NULL,
    FECULTACTUALIZACION  DATETIME        NOT NULL
);



CREATE TABLE dbo.STG_DGARANTIA (
    CODTIPOGARANTIA   VARCHAR(5)   NULL,
    DESTIPOGARANTIA   VARCHAR(80)  NULL,
    CODCLASE          VARCHAR(2)   NULL,
    DESCLASE          VARCHAR(30)  NULL,
    CODTIPOCLASE      VARCHAR(2)   NULL,
    DESTIPOCLASE      VARCHAR(50)  NULL,
    CODSUBTIPOCLASE   VARCHAR(2)   NULL,
    DESSUBTIPOCLASE   VARCHAR(50)  NULL
);



CREATE TABLE dbo.STG_DGRUPOCREDITO (
    CCODCONVEN           VARCHAR(6)     NULL,
    CDESCONVEN           VARCHAR(80)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DJEFEREGIONAL (
    CCODPERSON           VARCHAR(6)     NOT NULL,
    CNOMPERSON           VARCHAR(120)   NULL,
    DFECFINROT           DATETIME       NULL,
    NCODZONINS           INT            NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DMEDIOPAGO (
    CCODTIPPAG           VARCHAR(1)     NOT NULL,
    CDESTIPPAG           VARCHAR(30)    NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DMODALIDAD (
    CCODMODCRE           VARCHAR(2)     NOT NULL,
    CDESMODCRE           VARCHAR(20)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DMONEDA (
    CCODTIPMON           VARCHAR(1)     NULL,
    CDESTIPMON           VARCHAR(30)    NULL,
    CDESCORTA            VARCHAR(10)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DNIVELAPROBACION (
    CCODTIPACT           VARCHAR(3)     NULL,
    CDESTIPACT           VARCHAR(50)    NULL,
    NMONMINACT           NUMERIC(14,2)  NULL,
    NMONMAXACT           NUMERIC(14,2)  NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DPAIS (
    CCODPAIS             VARCHAR(3)     NOT NULL,
    CNOMPAIS             VARCHAR(50)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DPRODUCTO (
    CCODTIPCRE           VARCHAR(2)     NULL,
    CCODPRODUC           VARCHAR(2)     NULL,
    CCODSUBPRO           VARCHAR(2)     NULL,
    CDESTIPCRE           VARCHAR(100)   NULL,
    CDESSUBTIP           VARCHAR(100)   NULL,
    CDESPROCRE           VARCHAR(100)   NULL,
    CDESSUBCRE           VARCHAR(100)   NULL,
    FECHAINICIOVIG       DATETIME2(7)   NULL,
    FECHAFINVIG          DATETIME2(7)   NULL,
    FLAGESTADO           VARCHAR(1)     NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DRECURSO (
    cCodTipRec           CHAR(2)        NOT NULL,
    cDesTipRec           VARCHAR(20)    NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL
);


CREATE TABLE dbo.STG_DSECTORECONOMICO (
    cCodSecEco           CHAR(1)        NOT NULL,
    cDesSecEco           VARCHAR(100)   NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL
);


CREATE TABLE dbo.STG_DSOLICITUD (
    NNUMORDREM           NUMERIC(19,0)   NULL,
    CCODSOLCRE           VARCHAR(10)     NULL,
    CCODLINCRE           VARCHAR(10)     NULL,
    CCODCLIENT           VARCHAR(12)     NULL,
    CCODEXPCLI           VARCHAR(9)      NULL,
    CCODESTSOL           VARCHAR(1)      NULL,
    CCODISTSOL           VARCHAR(2)      NULL,
    CCODMONEDA           VARCHAR(1)      NULL,
    GRUPOCREDITO         VARCHAR(6)      NULL,
    CTIPTASCOM           VARCHAR(2)      NULL,
    CTIPTASMOR           VARCHAR(2)      NULL,
    NIVELAPROBACION      VARCHAR(3)      NULL,
    CCODCOMITE           VARCHAR(3)      NULL,
    CCODTIPCRE           VARCHAR(2)      NULL,
    CCODPRODUC           VARCHAR(2)      NULL,
    CCODSUBPRO           VARCHAR(2)      NULL,
    CCODTIPREC           VARCHAR(2)      NULL,
    CCODRECURS           VARCHAR(2)      NULL,
    CCODMODCRE           VARCHAR(2)      NULL,
    CCODCIIUSOL          VARCHAR(4)      NULL,
    CCODMODDES           VARCHAR(1)      NULL,
    CCODTIPSOL           VARCHAR(3)      NULL,
    CDESCRITIP           VARCHAR(40)     NULL,
    CCODMOTSOL           VARCHAR(1)      NULL,
    CDESMOTSOL           VARCHAR(50)     NULL,
    NMONSOLCRE           NUMERIC(14,2)   NULL,
    NNUMCUOSOL           INT             NULL,
    NPLASOLCRE           INT             NULL,
    DFECOSOLCRE          DATETIME2(7)    NULL,
    CCODUSUSOL           VARCHAR(6)      NULL,
    CMONEDAAPR           VARCHAR(1)      NULL,
    NMONAPRCRE           NUMERIC(14,2)   NULL,
    NNUMCUOAPR           INT             NULL,
    NNUMDIAGRA           INT             NULL,
    NDIAFECFIJ           INT             NULL,
    NPLAAPRCRE           INT             NULL,
    CTIPPERIODO          VARCHAR(1)      NULL,
    CDESPERIODO          VARCHAR(30)     NULL,
    CCODTIPCUO           VARCHAR(1)      NULL,
    CDESCRICUO           VARCHAR(40)     NULL,
    CLIBAMOCRE           VARCHAR(1)      NULL,
    DFECAPRCRE           DATETIME2(7)    NULL,
    NNROLINFIN           INT             NULL,
    NNROTASCOM           INT             NULL,
    NTASINTCOM           NUMERIC(14,4)   NULL,
    NNROTASMOR           INT             NULL,
    NTASINTMOR           NUMERIC(14,4)   NULL,
    CCODUSUING           VARCHAR(6)      NULL,
    NNUMDIAGRAAPR        INT             NULL,
    CTIPCLICRE           VARCHAR(1)      NULL,
    CCODCORADE           VARCHAR(15)     NULL,
    CCODOFICIN           VARCHAR(3)      NULL,
    CCODJEFEREGIONAL     VARCHAR(6)      NULL,
    CCODADMINISTRADOR    VARCHAR(6)      NULL,
    CCODUSUANA           VARCHAR(6)      NULL,
    NNUMEVAMES           INT             NULL,
    FECHAMIN             DATETIME2(7)    NULL,
    FECHAMAX             DATETIME2(7)    NULL,
    CCODNIVEL            VARCHAR(2)      NULL,
    CCODSUBNIV           VARCHAR(1)      NULL,
    CCODCLASUB           VARCHAR(2)      NULL,
    NCODPAPAPR           INT             NULL,
    CDESCLAANA           VARCHAR(150)    NULL
);



CREATE TABLE dbo.STG_DSOLICITUDESTADO (
    CCODESTSOL           VARCHAR(1)     NOT NULL,
    CDESCRIEST           VARCHAR(40)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DSOLICITUDSITUACION (
    CCODSITSOL           VARCHAR(2)     NOT NULL,
    CDESSITSOL           VARCHAR(40)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DSUBGERENTETERRITORIAL (
    CCODPERSON           CHAR(6)        NOT NULL,
    CNOMPERSON           VARCHAR(120)   NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL
);


CREATE TABLE dbo.STG_DSUBJEFETERRITORIALREC (
    PKSUBJEFETER         INT            NULL,
    CODSUBJEFETER        CHAR(6)        NULL,
    NOMSUBJEFETER        VARCHAR(100)   NULL,
    CODAGENCIA           CHAR(3)        NULL,
    LESTADOREG           BIT            NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DSUBRECURSO (
    CCODRECURS           VARCHAR(2)     NULL,
    CCODTIPREC           VARCHAR(2)     NULL,
    CDESRECURS           VARCHAR(40)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);



CREATE TABLE dbo.STG_DTERRITORIO (
    CODTERRITORIO        CHAR(2)        NULL,
    DESTERRITORIO        VARCHAR(20)    NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL
);


CREATE TABLE dbo.STG_DTIPOCREDITO (
    CCODTIPCRE           VARCHAR(2)     NULL,
    CDESTIPCRE           VARCHAR(100)   NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL
);



CREATE TABLE dbo.STG_DTIPODOCUMENTOIDENTIDAD (
    CCODTIPDOCID         VARCHAR(1)     NOT NULL,
    CDESTIPDOCID         VARCHAR(50)    NULL,
    CDESCORTA            VARCHAR(15)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DTIPOEXCEPCIONGARANTIA (
    CNOMBREPAR           VARCHAR(30)    NULL,
    CDESPARCRE           VARCHAR(70)    NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DTIPOEXCEPCIONPARAMETRO (
    NTIPVALIDA           INT            NULL,
    NCODPAREVA           INT            NOT NULL,
    CPAREVAVAL           VARCHAR(15)    NULL,
    CDESEVAVAL           VARCHAR(100)   NULL,
    FECULTACTUALIZACION  DATETIME       NULL,
    LESTEVAVAL           INT            NULL
);


CREATE TABLE dbo.STG_DTIPOOPERACION (
    CCODTIPOPE           VARCHAR(4)     NOT NULL,
    CDESTIPOPE           VARCHAR(50)    NULL,
    FECULTACTUALIZACION  DATETIME       NULL
);


CREATE TABLE dbo.STG_DTIPOTASA (
    CCODTIPTAS           VARCHAR(2)     NULL,
    CDESTIPTAS           VARCHAR(50)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DTIPOVIA (
    CCODTIPVIA           VARCHAR(2)     NOT NULL,
    CNOMTIPVIA           VARCHAR(50)    NULL,
    CABRVTIPVIA          VARCHAR(15)    NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DUBIGEO (
    CCODDEPART           VARCHAR(2)     NOT NULL,
    CNOMDEPART           VARCHAR(100)   NULL,
    CCODPROVIN           VARCHAR(2)     NOT NULL,
    CNOMPROVIN           VARCHAR(100)   NULL,
    CCODDISTRI           VARCHAR(2)     NOT NULL,
    CNOMDISTRI           VARCHAR(100)   NULL,
    CCODZONA             VARCHAR(3)     NOT NULL,
    CNOMZONA             VARCHAR(100)   NULL,
    FECULTACTUALIZACION  DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_DZONA (
    nCodZona             INT            NOT NULL,
    cDesZona             VARCHAR(60)    NULL,
    FECULTACTUALIZACION  DATETIME       NOT NULL,
    nOrdVisual           INT            NULL
);


CREATE TABLE dbo.STG_FCUENTACREDITO (
    PERIODODIA INT NULL,
    CCODCTACRE VARCHAR(18) NULL,
    CCODCLIENTE VARCHAR(12) NULL,
    CCODSOLCRE VARCHAR(10) NULL,
    CESTCRECON VARCHAR(1) NULL,
    CCODTIPCRE VARCHAR(2) NULL,
    CCODPRODUC VARCHAR(2) NULL,
    CCODSUBPRO VARCHAR(2) NULL,
    CCODTIPREC VARCHAR(2) NULL,
    CCODRECURS VARCHAR(2) NULL,
    CCODTIPMON VARCHAR(1) NULL,
    CCODMODCRE VARCHAR(2) NULL,
    CTIPTASCOM VARCHAR(2) NULL,
    CTIPTASMOR VARCHAR(2) NULL,
    CCODCONVEN VARCHAR(6) NULL,
    CCODACTIVI VARCHAR(6) NULL,
    CCONDICCON VARCHAR(2) NULL,
    CCODCLACAR VARCHAR(2) NULL,
    CCODCLAURI VARCHAR(2) NULL,
    CCODOFICIN VARCHAR(3) NULL,
    CCODMOTCAN VARCHAR(1) NULL,
    CTIPTASCOMJUD VARCHAR(2) NULL,
    CCODJEFEREGIONAL VARCHAR(6) NULL,
    ADMINISTRADOR VARCHAR(6) NULL,
    CCODUSUANA VARCHAR(6) NULL,
    NCODPAPAPR INT NULL,
    CCODNIVEL VARCHAR(2) NULL,
    CCODSUBNIV VARCHAR(1) NULL,
    CCODCLASUB VARCHAR(2) NULL,
    CDESCLASUB VARCHAR(150) NULL,
    NNUMCUOAPR INT NULL,
    NNUMDIAAPR INT NULL,
    NNUMDIAGRA INT NULL,
    NDIAFECFIJ INT NULL,
    CCODTIPCUO VARCHAR(1) NULL,
    CTIPPERIODO VARCHAR(1) NULL,
    CCODPLAZO VARCHAR(1) NULL,
    CCODULTDES VARCHAR(2) NULL,
    CCODLINCRE VARCHAR(10) NULL,
    NNROTASCOM INT NULL,
    NTASINTCOM DECIMAL(14,4) NULL,
    NNROTASMOR INT NULL,
    NTASINTMOR DECIMAL(14,4) NULL,
    NDIAATRCRE INT NULL,
    DFECCULCRE DATETIME2(7) NULL,
    DFEGCENCRE DATETIME2(7) NULL,
    DFEDESCRE DATETIME2(7) NULL,
    NTIPCAMDES DECIMAL(8,4) NULL,
    CCODTANOR VARCHAR(40) NULL,
    CCODTAVEN VARCHAR(40) NULL,
    CLIBAMOCRE VARCHAR(1) NULL,
    CCODREFINA VARCHAR(1) NULL,
    CCOODREESTR VARCHAR(1) NULL,
    CCODREPROG VARCHAR(1) NULL,
    CCODJUDICI VARCHAR(1) NULL,
    CCODCASTIG VARCHAR(1) NULL,
    CINDINUEREP VARCHAR(1) NULL,
    TIPCLIENTENUEVOMACHAYO INT NULL,
    TIPCLIENTENUEVO INT NULL,
    CLIENTECARTERA INT NULL,
    NMONAPRCRE DECIMAL(14,4) NULL,
    NMONCAPDES DECIMAL(14,4) NULL,
    NMONCAPPAG DECIMAL(14,4) NULL,
    NMONINTPRO DECIMAL(14,4) NULL,
    NMONINTFEC DECIMAL(14,4) NULL,
    NMONINTPAG DECIMAL(14,4) NULL,
    NMONMORPRO DECIMAL(14,4) NULL,
    NMONMORPAG DECIMAL(14,4) NULL,
    NMONGASPRO DECIMAL(14,4) NULL,
    NMONGASPAG DECIMAL(14,4) NULL,
    NMONSALNOR DECIMAL(14,4) NULL,
    NMONSALVEN DECIMAL(14,4) NULL,
    NCOSEFEACT DECIMAL(14,4) NULL,
    CTIPTASMOJUD VARCHAR(2) NULL,
    DFECCASCRE DATETIME2(7) NULL,
    DFECINGJUD DATETIME2(7) NULL,
    NDIAATRINI INT NULL,
    NMONCAPCAS DECIMAL(14,4) NULL,
    NMONCAPGEN DECIMAL(14,4) NULL,
    NMONCAPINI DECIMAL(14,4) NULL,
    NMONCAPPAGJUD DECIMAL(14,4) NULL,
    NMONGASCAS DECIMAL(14,4) NULL,
    NMONGASGEN DECIMAL(14,4) NULL,
    NMONGASINI DECIMAL(14,4) NULL,
    NMONGASPAGJUD DECIMAL(14,4) NULL,
    NMONINTCAS DECIMAL(14,4) NULL,
    NMONINTGEN DECIMAL(14,4) NULL,
    NMONINTINI DECIMAL(14,4) NULL,
    NMONINTPAGJUD DECIMAL(14,4) NULL,
    NMONMORCAS DECIMAL(14,4) NULL,
    NMONMORGEN DECIMAL(14,4) NULL,
    NMONMORINI DECIMAL(14,4) NULL,
    NMONMORPAGJUD DECIMAL(14,4) NULL,
    NMONSALCAP DECIMAL(14,4) NULL,
    NMONSALGAS DECIMAL(14,4) NULL,
    NMONSALINT DECIMAL(14,4) NULL,
    NMONSALMOR DECIMAL(14,4) NULL,
    NTASINTCOMJUD DECIMAL(14,4) NULL,
    NTASINTMORJUD DECIMAL(14,4) NULL,
    CAR_CON_CAPITAL DECIMAL(14,4) NULL,
    CAR_VIG_CAPITAL DECIMAL(14,4) NULL,
    CAR_VIG_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_VIG_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_VIG_GASTOS DECIMAL(14,4) NULL,
    CAR_VEN_CAPITAL DECIMAL(14,4) NULL,
    CAR_VEN_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_VEN_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_VEN_GASTOS DECIMAL(14,4) NULL,
    CAR_REF_CAPITAL DECIMAL(14,4) NULL,
    CAR_REF_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_REF_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_REF_GASTOS DECIMAL(14,4) NULL,
    CAR_REP_CAPITAL DECIMAL(14,4) NULL,
    CAR_REP_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_REP_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_REP_GASTOS DECIMAL(14,4) NULL,
    CAR_AMP_CAPITAL DECIMAL(14,4) NULL,
    CAR_AMP_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_AMP_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_AMP_GASTOS DECIMAL(14,4) NULL,
    CAR_JUD_CAPITAL DECIMAL(14,4) NULL,
    CAR_CON_GASTOS DECIMAL(14,4) NULL,
    CAR_CON_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_CON_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_CAS_CAPITAL DECIMAL(14,4) NULL,
    CAR_JUD_GASTOS DECIMAL(14,4) NULL,
    CAR_JUD_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_JUD_INT_MORATORIO DECIMAL(14,4) NULL,
    CAR_CAS_GASTOS DECIMAL(14,4) NULL,
    CAR_CAS_INT_COMPENSATORIO DECIMAL(14,4) NULL,
    CAR_CAS_INT_MORATORIO DECIMAL(14,4) NULL,
    CCODORDENRELACIONPAGO VARCHAR(4) NULL,
    MONTOSALDOCUENTA DECIMAL(14,4) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_GENTESTCIVIL (
    CCODESTCIV VARCHAR(1) NULL,
    CDESESTCIV VARCHAR(50) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);



CREATE TABLE dbo.STG_GENTOFICINAS (
    CCODOFICIN VARCHAR(3) NULL,
    CDESOFICIN VARCHAR(100) NULL,
    CCODDEPART VARCHAR(2) NULL,
    CCODPROVIN VARCHAR(2) NULL,
    CCODDISTR VARCHAR(2) NULL,
    CCODZONA VARCHAR(3) NULL,
    CTIPOIFICIN VARCHAR(1) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_GENTOFIZONAS (
    NCODZONA INT NULL,
    CCODOFICIN VARCHAR(3) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);

CREATE TABLE dbo.STG_GENTTIPOOFICIN (
    CTIPOFICIN VARCHAR(1) NULL,
    CDESTIPO VARCHAR(100) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_GENTZONAS (
    NCODZONA INT NULL,
    CDESZONA VARCHAR(60) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_KPYAMSOLICITUD_DASESOR (
    CCODUSUANA VARCHAR(6) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_KPYMCRECONVEN_DASESOR (
    CCODUSUANA VARCHAR(6) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_SIMPERSONAL_DASESOR (
    CCODPERSON VARCHAR(6) NULL,
    CNOMPERSON VARCHAR(120) NULL,
    CCODGRUPER VARCHAR(3) NULL,
    CCODESTPER VARCHAR(1) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_TEMP_CURFUEING (
    REG DECIMAL(19,0) NULL,
    CCODCLIENTE VARCHAR(12) NULL,
    CCODEMPLEADOR VARCHAR(12) NULL,
    CCODTIPFIN VARCHAR(1) NULL,
    NMONINGNET DECIMAL(12,2) NULL,
    CANOINIFIN VARCHAR(4) NULL,
    DEFECREGFIN DATETIME2(7) NULL,
    CCODACTIVI VARCHAR(6) NULL,
    CNOMEMP VARCHAR(120) NULL,
    CNRODOCEMP VARCHAR(15) NULL,
    CCODDEPART VARCHAR(2) NULL,
    CCODPROVIN VARCHAR(2) NULL,
    CCODDISTRI VARCHAR(2) NULL,
    CCODZONA VARCHAR(3) NULL,
    CDIREMP VARCHAR(120) NULL,
    CNROTELEMP VARCHAR(12) NULL,
    CCODTIPVIA VARCHAR(2) NULL
);

CREATE TABLE dbo.STG_TEMP_DASESOR (
    CODASESOR VARCHAR(6) NULL,
    NOMASESOR VARCHAR(120) NULL,
    FUENTE VARCHAR(20) NULL,
    FECULTACTUALIZACION DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUD1 (
    CCODSOLCRE VARCHAR(10) NULL,
    FECHAMIN DATETIME2(7) NULL,
    FECHAMAX DATETIME2(7) NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUD2 (
    CCODSOLCRE         VARCHAR(10)     NULL,
    CCODLINCRE         VARCHAR(10)     NULL,
    CCODCLIENT         VARCHAR(12)     NULL,
    CCODEXPCLI         VARCHAR(9)      NULL,
    CCODESTSOL         VARCHAR(1)      NULL,
    CCODDISTSOL        VARCHAR(2)      NULL,
    CCODMONEDA         VARCHAR(1)      NULL,
    GRUPOCREDITO       VARCHAR(6)      NULL,
    CTIPTASCOM         VARCHAR(2)      NULL,
    CTIPTASMOR         VARCHAR(2)      NULL,
    NIVELAPROBACION    VARCHAR(3)      NULL,
    CCODCOMITE         VARCHAR(3)      NULL,
    CCODTIPCRE         VARCHAR(2)      NULL,
    CCODPRODUC         VARCHAR(2)      NULL,
    CCODSUBPRO         VARCHAR(2)      NULL,
    CCODTIPREC         VARCHAR(2)      NULL,
    CCODRECURS         VARCHAR(2)      NULL,
    CCODMODCRE         VARCHAR(2)      NULL,
    CCODCIIUSOL        VARCHAR(4)      NULL,
    CCODMODDES         VARCHAR(1)      NULL,
    CCODTIPSOL         VARCHAR(3)      NULL,
    CDESCRIP           VARCHAR(40)     NULL,
    CCODMOTSOL         VARCHAR(1)      NULL,
    CDESMOTSOL         VARCHAR(50)     NULL,
    NMONSOLCRE         DECIMAL(14,2)   NULL,
    NNUMCUOSOL         INT             NULL,
    NPLASOLCRE         INT             NULL,
    DFECSOLCRE         DATETIME2(7)    NULL,
    CCODUSUSOL         VARCHAR(6)      NULL,
    CMONEDAAPR         VARCHAR(1)      NULL,
    NMONAPRCRE         DECIMAL(14,2)   NULL,
    NNUMCUOAPR         INT             NULL,
    NNUMDIAGRAP        INT             NULL,
    NDIAFECFIJ         INT             NULL,
    NPLAAPRCRE         INT             NULL,
    CTIPPERIODO        VARCHAR(1)      NULL,
    CDESPERIODO        VARCHAR(30)     NULL,
    CCODTIPCUO         VARCHAR(1)      NULL,
    CDESCRICUO         VARCHAR(40)     NULL,
    CLIBAMOCRE         VARCHAR(1)      NULL,
    DFECPARCRE         DATETIME2(7)    NULL,
    NNROLINFIN         INT             NULL,
    NNROTASCOM         INT             NULL,
    NTASINTCOM         DECIMAL(14,4)   NULL,
    NNROTASMOR         INT             NULL,
    NTASINTMOR         DECIMAL(14,4)   NULL,
    CCODUSUING         VARCHAR(6)      NULL,
    NNUMDIAGRAPR       INT             NULL,
    CTIPCLICRE         VARCHAR(1)      NULL,
    CCODCORADE         VARCHAR(15)     NULL,
    CCODOFICIN         VARCHAR(3)      NULL,
    CCODJEFEREGIONAL   VARCHAR(6)      NULL,
    CODADMINISTRADOR   VARCHAR(6)      NULL,
    CCODUSUANA         VARCHAR(6)      NULL,
    FECHAMIN           DATETIME2(7)    NULL,
    NNUMEVAMES         INT             NULL,
    FECHAMAX           DATETIME2(7)    NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUDADM1 (
    CCODPERSON         VARCHAR(6)     NULL,
    CCODPERANT         VARCHAR(3)     NULL,
    CCODOFICIN         VARCHAR(3)     NULL,
    CNOMPERSON         VARCHAR(120)   NULL,
    CCODSEXO           VARCHAR(1)     NULL,
    DFENCNACPER        DATETIME2(7)   NULL,
    CCODNACION         VARCHAR(1)     NULL,
    CCODPAINAC         VARCHAR(3)     NULL,
    CCODDEPNAC         VARCHAR(3)     NULL,
    CCODPRONAC         VARCHAR(3)     NULL,
    CCODDISNAC         VARCHAR(3)     NULL,
    CCODZONNAC         VARCHAR(3)     NULL,
    CLUGNACPER         VARCHAR(20)    NULL,
    CPRONACPER         VARCHAR(20)    NULL,
    CDENPACPER         VARCHAR(20)    NULL,
    CCODTIPDOCID       VARCHAR(1)     NULL,
    CNUMDOCIDE         VARCHAR(15)    NULL,
    CCODTIPDOCTR       VARCHAR(1)     NULL,
    CNUMOTRDOC         VARCHAR(15)    NULL,
    CNUMLIBMIL         VARCHAR(15)    NULL,
    CCODGRUSAN         VARCHAR(2)     NULL,
    CCODESTCIV         VARCHAR(1)     NULL,
    NMEDESTPER         NUMERIC(6,2)   NULL,
    NMEDPESPER         NUMERIC(6,2)   NULL,
    NNUMHIJPER         INT            NULL,
    CCODPROFES         VARCHAR(6)     NULL,
    CDESPROFES         VARCHAR(60)    NULL,
    CCODPAIDOM         VARCHAR(3)     NULL,
    CCODDEPDOM         VARCHAR(3)     NULL,
    CCODPRODOM         VARCHAR(3)     NULL,
    CCODDISDOM         VARCHAR(3)     NULL,
    CCODZONDOM         VARCHAR(3)     NULL,
    CDIRDOMPER         VARCHAR(120)   NULL,
    CCODCLIPER         VARCHAR(12)    NULL,
    DFECINGINS         DATETIME2(7)   NULL,
    DFECESINS          DATETIME2(7)   NULL,
    CNROCTAPER         VARCHAR(18)    NULL,
    CCLAUNIPER         VARCHAR(10)    NULL,
    CCODAFPAPER        VARCHAR(2)     NULL,
    CNUMAFPAPER        VARCHAR(15)    NULL,
    DFECINGAFP         DATETIME2(7)   NULL,
    CCODSNPPER         VARCHAR(2)     NULL,
    CNUMSSPPER         VARCHAR(15)    NULL,
    DFECINGSSP         DATETIME2(7)   NULL,
    DFECCSTSPER        DATETIME2(7)   NULL,
    NNUMCSTSIND        NUMERIC(2,0)   NULL,
    CCODRELINS         VARCHAR(1)     NULL,
    CCODESTPER         VARCHAR(1)     NULL,
    CCODCONDPER        VARCHAR(1)     NULL,
    CCODAREACMAC       VARCHAR(3)     NULL,
    CCODGRUPER         VARCHAR(3)     NULL,
    CCODCLASPER        VARCHAR(3)     NULL,
    CCODGRUHOR         VARCHAR(3)     NULL,
    LPERFUNSBS         INT            NULL,
    CCTRFCCHPER        VARCHAR(5)     NULL,
    CCODREMADI         VARCHAR(1)     NULL,
    CCODUSUREG         VARCHAR(6)     NULL,
    DFECCREGPER        DATETIME2(7)   NULL,
    CCODUSUMOD         VARCHAR(6)     NULL,
    DFECCMODREG        DATETIME2(7)   NULL,
    CCTRFPERELI        VARCHAR(1)     NULL,
    LCONTESTADO        INT            NULL,
    CCODPERPER         VARCHAR(1)     NULL,
    CFLAG              VARCHAR(1)     NULL,
    CNUMTELPER         VARCHAR(20)    NULL,
    CCODMOTCES         VARCHAR(2)     NULL,
    CDESCESE           VARCHAR(250)   NULL,
    CCODNIVEL          VARCHAR(2)     NULL,
    CCODGRUOCU         VARCHAR(2)     NULL,
    CCODGRAEST         VARCHAR(2)     NULL,
    CCODTITEST         VARCHAR(2)     NULL,
    CCODCAREST         VARCHAR(3)     NULL,
    CCODCURSOS         VARCHAR(30)    NULL,
    CAUDITSTATION      VARCHAR(30)    NULL,
    CAUDITUSER         VARCHAR(30)    NULL,
    CAUDITCLIENT       VARCHAR(50)    NULL,
    DAUDITDATE         DATETIME2(7)   NULL,
    CCODORGANI         VARCHAR(12)    NULL,
    CCONDICFUN         VARCHAR(3)     NULL,
    CCLASIFCAP         VARCHAR(3)     NULL,
    CCODDISPEN         VARCHAR(1)     NULL,
    CCODCAPAPR         VARCHAR(7)     NULL,
    CCODSUBNIV         VARCHAR(1)     NULL,
    CCODCLASUB         VARCHAR(2)     NULL,
    CCODSALCAR         VARCHAR(3)     NULL,
    CCODREGPEN         VARCHAR(2)     NULL,
    CCODDOCUPAC        VARCHAR(6)     NULL,
    LPERCONFIA         INT            NULL,
    LAPODERADO         INT            NULL,
    NCODPAPAPR         INT            NULL,
    CCODESTABL         VARCHAR(4)     NULL,
    NCODINGPER         INT            NULL,
    CTIPCOMVAR         VARCHAR(1)     NULL,
    CDESMENEST         VARCHAR(150)   NULL,
    LPERCONDIR         INT            NULL,
    CDESCARPER         VARCHAR(120)   NULL
);

CREATE TABLE dbo.STG_TEMP_DSOLICITUDADMF1 (
    DFECFINROT          datetime2(7) NULL,
    NNUMORDREM          numeric(19,0) NULL,
    CCODPERSON          varchar(6) NULL,
    CCODPERANT          varchar(3) NULL,
    CCODOFICIN          varchar(3) NULL,
    CNOMPERSON          varchar(120) NULL,
    CCODSEXO            varchar(1) NULL,
    DFECNACPER          datetime2(7) NULL,
    CCODNACION          varchar(1) NULL,
    CCODPAINAC          varchar(3) NULL,
    CCODDEPNAC          varchar(3) NULL,
    CCODPRONAC          varchar(3) NULL,
    CCODDISNAC          varchar(3) NULL,
    CCODZONNAC          varchar(3) NULL,
    CLUGNACPER          varchar(20) NULL,
    CPRONACPER          varchar(20) NULL,
    CDEPNACPER          varchar(20) NULL,
    CCODTIPDOCID        varchar(1) NULL,
    CNUMDOCIDE          varchar(15) NULL,
    CCODTIPDOCTR        varchar(1) NULL,
    CNUMOTRDOC          varchar(15) NULL,
    CNUMLIBMIL          varchar(15) NULL,
    CCODGRUSAN          varchar(2) NULL,
    CCODESTCIV          varchar(1) NULL,
    NMEDESTPER          numeric(6,2) NULL,
    NMEDESPER           numeric(6,2) NULL,
    NNUMHIJPER          int NULL,
    CCODPROFES          varchar(6) NULL,
    CDESPROFES          varchar(60) NULL,
    CCODPAIDOM          varchar(3) NULL,
    CCODDEPDOM          varchar(3) NULL,
    CCODPRODOM          varchar(3) NULL,
    CCODDISDOM          varchar(3) NULL,
    CCODZONDOM          varchar(3) NULL,
    CDIRDOMPER          varchar(120) NULL,
    CCODCLIPER          varchar(12) NULL,
    DFECINGINS          datetime2(7) NULL,
    DFECCESINS          datetime2(7) NULL,
    CNROCTAPER          varchar(18) NULL,
    CCLAUNIPER          varchar(10) NULL,
    CCODAFPAPER         varchar(2) NULL,
    CNUMAFPAPER         varchar(15) NULL,
    DFECINGAFP          datetime2(7) NULL,
    CCODSNPPER          varchar(2) NULL,
    CNUMSSPPER          varchar(15) NULL,
    DFECINGSSP          datetime2(7) NULL,
    DFECCSTPER          datetime2(7) NULL,
    NNUMCTSIND          numeric(2,0) NULL,
    CCODRELINS          varchar(1) NULL,
    CCODESTPER          varchar(1) NULL,
    CCODCONDPER         varchar(1) NULL,
    CCODAREACMAC        varchar(3) NULL,
    CCODGRUPER          varchar(3) NULL,
    CCODCLASPER         varchar(3) NULL,
    CCODGRUHOR          varchar(3) NULL,
    LPERFUNSBS          int NULL,
    CCTRFCHPER          varchar(5) NULL,
    CCODREMADI          varchar(1) NULL,
    CCODUSUREG          varchar(6) NULL,
    DFECREGPER          datetime2(7) NULL,
    CCODUSUMOD          varchar(6) NULL,
    DFECMODREG          datetime2(7) NULL,
    CCTRPERELI          varchar(1) NULL,
    LCONESTADO          int NULL,
    CCODPERPER          varchar(1) NULL,
    CFLAG               varchar(1) NULL,
    CNUMTELPER          varchar(20) NULL,
    CCODMOTCES          varchar(1) NULL,
    CDESCESCE           varchar(250) NULL,
    CCODNIVEL           varchar(2) NULL,
    CCODGRUOCU          varchar(2) NULL,
    CCODGRAEST          varchar(2) NULL,
    CCODTITEST          varchar(2) NULL,
    CCODCAREST          varchar(3) NULL,
    CAUDITUSER          varchar(30) NULL,
    CAUDITSTATION       varchar(30) NULL,
    CAUDITCLIENT        varchar(50) NULL,
    DAUDITDATE          datetime2(7) NULL,
    CCODORGANI          varchar(12) NULL,
    CCONDICFUN          varchar(3) NULL,
    CCLASIFCAP          varchar(3) NULL,
    CCODDISPEN          varchar(1) NULL,
    CCODCAPAPR          varchar(7) NULL,
    CCODSUBNIV          varchar(1) NULL,
    CCODCLASUB          varchar(2) NULL,
    CCODSALCAR          varchar(3) NULL,
    CCODREGPEN          varchar(2) NULL,
    CCODOCUPAC          varchar(6) NULL,
    LPERCONFIA          int NULL,
    LAPODERADO          int NULL,
    NCODPAPAPR          int NULL,
    CCODESTABL          varchar(4) NULL,
    NCODINGPER          int NULL,
    CTIPCOMVAR          varchar(1) NULL,
    CDESMENESET         varchar(150) NULL,
    LPERCONDIR          int NULL,
    CDESCARPER          varchar(120) NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUDASESORF (
    CCODPERSON varchar(6) NULL,
    CCODPERANT varchar(3) NULL,
    CCODOFICIN varchar(3) NULL,
    CNOMPERSON varchar(120) NULL,
    CCODSEXO varchar(1) NULL,
    DFECNACPER datetime2(7) NULL,
    CCODNACION varchar(1) NULL,
    CCODPAINAC varchar(3) NULL,
    CCODDEPNAC varchar(3) NULL,
    CCODPRONAC varchar(3) NULL,
    CCODDISNAC varchar(3) NULL,
    CCODZONNAC varchar(3) NULL,
    CLUGNACPER varchar(20) NULL,
    CPRONACPER varchar(20) NULL,
    CDEPNACPER varchar(20) NULL,
    CCODTIPDOCID varchar(1) NULL,
    CNUMDOCIDE varchar(15) NULL,
    CCODTIPDOCTR varchar(1) NULL,
    CNUMOTRDOC varchar(15) NULL,
    CNUMLIBMIL varchar(15) NULL,
    CCODGRUSAN varchar(2) NULL,
    CCODESTCIV varchar(1) NULL,
    NMEDESTPER numeric(6,2) NULL,
    NMEDPESPER numeric(6,2) NULL,
    NNUMHIJPER int NULL,
    CCODPROFES varchar(6) NULL,
    CDESPROFES varchar(60) NULL,
    CCODPAIDOM varchar(3) NULL,
    CCODDEPDOM varchar(3) NULL,
    CCODPRODOM varchar(3) NULL,
    CCODDISDOM varchar(3) NULL,
    CCODZONDOM varchar(3) NULL,
    CDIRDOMPER varchar(120) NULL,
    CCODCLIPER varchar(12) NULL,
    DFECINGINS datetime2(7) NULL,
    DFECCESINS datetime2(7) NULL,
    CNROCTAPER varchar(18) NULL,
    CCLAUNIPER varchar(10) NULL,
    CCODAFPPER varchar(2) NULL,
    CNUMAFPPER varchar(15) NULL,
    DFECINGAFP datetime2(7) NULL,
    CCODSNPPER varchar(2) NULL,
    CNUMSSPPER varchar(15) NULL,
    DFECINGSSP datetime2(7) NULL,
    DFECCTSPER datetime2(7) NULL,
    NNUMCTSIND numeric(2,0) NULL,
    CCODRELINS varchar(1) NULL,
    CCODESTPER varchar(1) NULL,
    CCODCONDPER varchar(1) NULL,
    CCODAREACMAC varchar(3) NULL,
    CCODGRUPER varchar(3) NULL,
    CCODCLASPER varchar(3) NULL,
    CCODGRUHOR varchar(3) NULL,
    LPERFUNSBS int NULL,
    CCTRFCHPER varchar(5) NULL,
    CCODREMADI varchar(1) NULL,
    CCODUSUREG varchar(6) NULL,
    DFECREGPER datetime2(7) NULL,
    CCODUSUMOD varchar(6) NULL,
    DFECMODREG datetime2(7) NULL,
    CCTRPERELI varchar(1) NULL,
    LCONESTADO int NULL,
    CCODPERPER varchar(1) NULL,
    CFLAG varchar(1) NULL,
    CNUMTELPER varchar(20) NULL,
    CCODMOTCES varchar(2) NULL,
    CDESECE varchar(250) NULL,
    CCODNIVEL varchar(2) NULL,
    CCODGRUOCU varchar(2) NULL,
    CCODGRAEST varchar(2) NULL,
    CCODTITEST varchar(2) NULL,
    CCODCAREST varchar(3) NULL,
    CAUDITUSER varchar(30) NULL,
    CAUDITSTATION varchar(30) NULL,
    CAUDITCLIENT varchar(50) NULL,
    DAUDITDATE datetime2(7) NULL,
    CCODORGANI varchar(12) NULL,
    CCONDICFUN varchar(3) NULL,
    CCLASIFCAP varchar(3) NULL,
    CCODDISPEN varchar(1) NULL,
    CCODCAPAPR varchar(7) NULL,
    CCODSUBNIV varchar(1) NULL,
    CCODCLASUB varchar(2) NULL,
    CCODSALCAR varchar(3) NULL,
    CCODREGPEN varchar(2) NULL,
    CCODCUPAC varchar(6) NULL,
    LPERCONFIA int NULL,
    LAPODERADO int NULL,
    NCODPAPAPR int NULL,
    CCODESTABL varchar(4) NULL,
    NCODINGPER int NULL,
    CTIPCOMVAR varchar(1) NULL,
    CDESMENEST varchar(150) NULL,
    LPERCONDIR int NULL,
    CDESCARPER varchar(120) NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUDJEFEF (
    DFECFINROT datetime2(7) NULL,
    NNUMORDREM decimal(19,0) NULL,
    CCODPERSON varchar(6) NULL,
    CCODASIRES varchar(3) NULL,
    NCODZONINS int NULL,
    DFECINIRES datetime2(7) NULL,
    DFECFINRES datetime2(7) NULL,
    LESTADOREG int NULL,
    CCODUSUREG varchar(6) NULL,
    DFECREGIST datetime2(7) NULL,
    CCODUSUMOD varchar(6) NULL,
    DFECMODREG datetime2(7) NULL,
    CCODZONCOM varchar(2) NULL,
    CNOMPERSON varchar(120) NULL,
    CDESCARPER varchar(120) NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUDSIPDASCROTPER (
    CCODPERSON        VARCHAR(6)     NULL,
    CCODDETASCR       VARCHAR(3)     NULL,
    LVIGAScROT        INT            NULL,
    LACTAScROT        INT            NULL,
    CCODAScROT        VARCHAR(3)     NULL,
    DfINIAScROT       DATETIME2(7)   NULL,
    DFfINAScROT       DATETIME2(7)   NULL,
    NDIASAScROT       INT            NULL,
    CCODCAScROT       VARCHAR(10)    NULL,
    CCODGRUPER        VARCHAR(3)     NULL,
    CCODOFICIN        VARCHAR(3)     NULL,
    CCODUSUMOD        VARCHAR(6)     NULL,
    DFECMODREG        DATETIME2(7)   NULL,
    CCODOFIORI        VARCHAR(3)     NULL,
    CAUDITUSER        VARCHAR(30)    NULL,
    CAUDITSTATION     VARCHAR(30)    NULL,
    CAUDITCLIENT      VARCHAR(50)    NULL,
    DAUDITDATE        DATETIME2(7)   NULL,
    CCODCLASPER       VARCHAR(3)     NULL,
    CCODORGANi        VARCHAR(12)    NULL,
    CCLASIFCAP        VARCHAR(3)     NULL,
    CCODAREACMAC      VARCHAR(3)     NULL,
    CCODCAPAPR        VARCHAR(7)     NULL,
    CCODNIVEL         VARCHAR(2)     NULL,
    CCODSUBNIV        VARCHAR(1)     NULL,
    CCODCLASUB        VARCHAR(2)     NULL,
    NCODPAPAPR        INT            NULL,
    CCODESTABL        VARCHAR(4)     NULL,
    CARCAScROT        VARCHAR(17)    NULL,
    CCODIGODOC        VARCHAR(8)     NULL,
    LESTENVIADO       INT            NULL,
    LESTVISDOC        INT            NULL,
    CUSUSVISDOC       VARCHAR(6)     NULL,
    DFEcVISDOC        DATETIME2(7)   NULL
);


CREATE TABLE dbo.STG_TEMP_DSOLICITUDSIPTCLASUBNIV (
    NCODPAPAPR     INT             NULL,
    CCODNIVEL      VARCHAR(2)      NULL,
    CCODSUBNIV     VARCHAR(1)      NULL,
    CCODCLASUB     VARCHAR(2)      NULL,
    CDESCLASUB     VARCHAR(150)    NULL,
    NREMBASICA     NUMERIC(12,2)   NULL,
    NINCENTVAR     NUMERIC(12,2)   NULL,
    NINCENTFIJO    NUMERIC(12,2)   NULL,
    LCONESTADO     INT             NULL,
    CCODUSUREG     VARCHAR(6)      NULL,
    DFECREGIST     DATETIME2(7)    NULL,
    CULTUSUMOD     VARCHAR(6)      NULL,
    DFECCULTMOD    DATETIME2(7)    NULL
);


CREATE TABLE dbo.STG_TEMP_FCUENTACREDITO_CLIENTE (
    CCODCTACRE   VARCHAR(18)  NULL,
    CCODCLIENTE  VARCHAR(12)  NULL,
    CCONDICCON   VARCHAR(2)   NULL,
    CCODULTPLA   VARCHAR(3)   NULL,
    CCODULTDES   VARCHAR(2)   NULL,
    CCODLINCRE   VARCHAR(10)  NULL
);


CREATE TABLE dbo.STG_TEMP_FCUENTACREDITO_CREDITO (
    CCODCTACRE    VARCHAR(18)    NULL,
    CCODSOLCRE    VARCHAR(10)    NULL,
    CESTCRECON    VARCHAR(1)     NULL,
    CCODTIPCRE    VARCHAR(2)     NULL,
    CCODPRODUC    VARCHAR(2)     NULL,
    CCODSUBPRO    VARCHAR(2)     NULL,
    CCODTIPREC    VARCHAR(2)     NULL,
    CCODRECURS    VARCHAR(2)     NULL,
    CCODTIPMON    VARCHAR(1)     NULL,
    CCODMODCRE    VARCHAR(2)     NULL,
    CTIPTASCOM    VARCHAR(2)     NULL,
    CTIPTASMOR    VARCHAR(2)     NULL,
    CCODCONVEN    VARCHAR(6)     NULL,
    CCODACTIVI    VARCHAR(6)     NULL,
    CCODCLACAR    VARCHAR(2)     NULL,
    CCODCLAURI    VARCHAR(2)     NULL,
    CCODOFICIN    VARCHAR(3)     NULL,
    CCODUSUANA    VARCHAR(6)     NULL,
    NNUMCUOAPR    INT            NULL,
    NNUMDIAAPR    INT            NULL,
    NNUMDIAGRA    INT            NULL,
    NDIAFECFIJ    INT            NULL,
    CCODTIPCUO    VARCHAR(1)     NULL,
    CTIPPERIODO   VARCHAR(1)     NULL,
    CCODPLAZO     VARCHAR(1)     NULL,
    NNROTASCOM    INT            NULL,
    NTASINTCOM    DECIMAL(14,4)  NULL,
    NNROTASMOR    INT            NULL,
    NTASINTMOR    DECIMAL(14,4)  NULL,
    NDIAATRCRE    INT            NULL,
    DFECCULCRE    DATETIME2(7)   NULL,
    DFEGCENCRE    DATETIME2(7)   NULL,
    DFECDECSRE    DATETIME2(7)   NULL,
    NTIPCAMDES    DECIMAL(8,4)   NULL,
    CCODCTANOR    VARCHAR(40)    NULL,
    CCODCTAVEN    VARCHAR(40)    NULL,
    CLIBAMOCRE    VARCHAR(1)     NULL,
    CCODREFINA    VARCHAR(1)     NULL,
    CCODREESTR    VARCHAR(1)     NULL,
    CCODREPROG    VARCHAR(1)     NULL,
    CCODJUDICI    VARCHAR(1)     NULL,
    CCODCASTIG    VARCHAR(1)     NULL,
    CINDNUEREP    VARCHAR(1)     NULL,
    NMONAPRCRE    DECIMAL(14,2)  NULL,
    NMONCAPDES    DECIMAL(14,2)  NULL,
    NMONCAPPAG    DECIMAL(14,2)  NULL,
    NMONINTPRO    DECIMAL(14,2)  NULL,
    NMONINTFEC    DECIMAL(14,2)  NULL,
    NMONINTPAG    DECIMAL(14,2)  NULL,
    NMONMORPRO    DECIMAL(14,2)  NULL,
    NMONMORPAG    DECIMAL(14,2)  NULL,
    NMONGASPRO    DECIMAL(14,2)  NULL,
    NMONGASPAG    DECIMAL(14,2)  NULL,
    NMONSALNOR    DECIMAL(14,2)  NULL,
    NMONSALVEN    DECIMAL(14,2)  NULL,
    NCOSEFEACT    DECIMAL(14,4)  NULL
);


CREATE TABLE dbo.STG_TEMP_FCUENTACREDITO_CREDJUDICIAL (
    CCODCTACRE   VARCHAR(18)    NULL,
    CTIPTASCOM   VARCHAR(2)     NULL,
    CTIPTASMOR   VARCHAR(2)     NULL,
    DFECINGJUD   DATETIME2(7)   NULL,
    NMONCAPINI   DECIMAL(14,2)  NULL,
    NMONINTINI   DECIMAL(14,2)  NULL,
    NMONMORINI   DECIMAL(14,2)  NULL,
    NMONGASINI   DECIMAL(14,2)  NULL,
    NDIAATRINI   INT            NULL,
    NMONINTGEN   DECIMAL(14,2)  NULL,
    NMONMORGEN   DECIMAL(14,2)  NULL,
    NMONGASGEN   DECIMAL(14,2)  NULL,
    NMONCAPGEN   DECIMAL(14,2)  NULL,
    NMONSALCAP   DECIMAL(14,2)  NULL,
    NMONSALINT   DECIMAL(14,2)  NULL,
    NMONSALMOR   DECIMAL(14,2)  NULL,
    NMONSALGAS   DECIMAL(14,2)  NULL,
    NMONCAPPAG   DECIMAL(14,2)  NULL,
    NMONINTPAG   DECIMAL(14,2)  NULL,
    NMONMORPAG   DECIMAL(14,2)  NULL,
    NMONGASPAG   DECIMAL(14,2)  NULL,
    NTASINTCOM   DECIMAL(14,4)  NULL,
    NTASINTMOR   DECIMAL(14,4)  NULL,
    CORDRECUPR   VARCHAR(4)     NULL,
    NMONCAPCAS   DECIMAL(14,2)  NULL,
    NMONINTCAS   DECIMAL(14,2)  NULL,
    NMONMORCAS   DECIMAL(14,2)  NULL,
    NMONGASCAS   DECIMAL(14,2)  NULL,
    DFECCASCRE   DATETIME2(7)   NULL,
    CCODMOTCAN   VARCHAR(1)     NULL
);


CREATE TABLE dbo.STG_TEMP_FCUENTACREDITO_OFIZONAS (
    CCODOFICIN  VARCHAR(3) NULL,
    LESTZONOFI  INT         NULL,
    NCODZONA    INT         NULL
);


CREATE TABLE dbo.STG_TEMP_SQL_FEVAL (
    CODSOLICITUD           VARCHAR(10)     NULL,
    NROEVALUACION          INT             NULL,
    CODSOLICITUDESTADO     VARCHAR(1)      NULL,
    CODSOLICITUDSITUACION  VARCHAR(2)      NULL,
    FECULTACTUALIZACION    DATETIME2(7)    NULL
);


CREATE TABLE dbo.STGDFUENTEINGRESO (
    CODFUENTEINGRESO   CHAR(1)        NOT NULL,
    DESFUENTEINGRESO   VARCHAR(40)    NULL,
    FECHAACTUALIZACION DATETIME       NULL
);


CREATE TABLE dbo.STGDTIPOINGRESO (
    CODTIPOINGRESO     CHAR(1)       NOT NULL,
    DESTIPOINGRESO     VARCHAR(40)   NULL,
    FECHAACTUALIZACION DATETIME      NULL
);









