apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: jupyterhub

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: jupyterhub
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: jupyterhub
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: jupyterhub
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [services]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: ["*"]